#!/usr/bin/env python3
"""Verify the shared gene-bank manifest (P2 gate; single home: ADR
.agents/notes/proposed/architecture/2026-09-06-p2-shared-consumer.md, D3).

The manifest is the bank's retrieval index (manifest.json at the repo root;
generated by scripts/gen-manifest.py). This gate makes drift a CI failure:
the committed manifest must describe exactly the genes/ tree.

Checks, for the repo root (default cwd):
  manifest.json
    - valid JSON; version == 1; genes is a list; refs unique and sorted
    - each entry has exactly {ref, path, summary, signals}
    - path is POSIX-relative, inside genes/<domain>/<id>.json, and exists
    - entry content matches the gene file byte-for-byte on
      {summary, signals} and anchor fields (id == stem, domain == parent dir)
  genes/ tree
    - every genes/<domain>/<id>.json appears in the manifest (no missing rows)

Usage: python3 scripts/verify-manifest.py [--repo ROOT]
       python3 scripts/verify-manifest.py --self-test   # offline fixture self-check
Exit code 0 = pass, 1 = violations.

Provenance: original to Noogenesis (2026-09-06, P2 implementation round).
"""

import json
import re
import sys
import tempfile
from pathlib import Path

KEBAB_RE = re.compile(r"^[a-z0-9]+(?:-[a-z0-9]+)*$")
ENTRY_FIELDS = {"ref", "path", "summary", "signals"}


def _scan_tree(repo: Path) -> dict[str, dict]:
    """Read genes/<domain>/<id>.json -> {ref: {path, id, domain, summary, signals}}."""
    out: dict[str, dict] = {}
    root = repo / "genes"
    if not root.is_dir():
        return out
    for domain_dir in sorted(p for p in root.iterdir() if p.is_dir()):
        for f in sorted(domain_dir.glob("*.json")):
            rel = f.relative_to(repo).as_posix()
            try:
                data = json.loads(f.read_text(encoding="utf-8"))
            except json.JSONDecodeError as e:
                out[f"{domain_dir.name}/{f.stem}"] = {"_error": f"{rel}: not valid JSON: {e}"}
                continue
            out[f"{domain_dir.name}/{f.stem}"] = {
                "path": rel, "id": data.get("id"), "domain": data.get("domain"),
                "summary": data.get("summary"), "signals": data.get("signals"),
            }
    return out


def verify(repo: Path) -> tuple[int, list[str]]:
    errors: list[str] = []
    mpath = repo / "manifest.json"
    if not mpath.is_file():
        tree = _scan_tree(repo)
        return len(tree) + 1, ["manifest.json missing at repo root (run scripts/gen-manifest.py)"]
    try:
        manifest = json.loads(mpath.read_text(encoding="utf-8"))
    except json.JSONDecodeError as e:
        return 1, [f"manifest.json: not valid JSON: {e}"]
    if not isinstance(manifest, dict):
        return 1, ["manifest.json: must be a JSON object"]
    if manifest.get("version") != 1:
        errors.append("manifest.json: version must be 1")
    genes = manifest.get("genes")
    if not isinstance(genes, list):
        return len(errors) + 1, errors + ["manifest.json: genes must be a list"]

    tree = _scan_tree(repo)
    rows: dict[str, dict] = {}
    for i, entry in enumerate(genes):
        where = f"manifest.json genes[{i}]"
        if not isinstance(entry, dict) or set(entry) != ENTRY_FIELDS:
            errors.append(f"{where}: entry must have exactly {sorted(ENTRY_FIELDS)}")
            continue
        ref = entry.get("ref")
        segs = ref.split("/") if isinstance(ref, str) else []
        if len(segs) != 2 or not all(KEBAB_RE.match(s) for s in segs):
            errors.append(f"{where}: ref must be two kebab segments <domain>/<id>")
            continue
        if ref in rows:
            errors.append(f"{where}: duplicate ref {ref}")
            continue
        rows[ref] = entry
        p = entry.get("path")
        if p != f"genes/{ref}.json":
            errors.append(f"{where}: path must be genes/<domain>/<id>.json matching ref, got {p!r}")
            continue
        f = repo / p
        if not f.is_file():
            errors.append(f"{where}: path does not exist: {p}")
            continue
        try:
            data = json.loads(f.read_text(encoding="utf-8"))
        except json.JSONDecodeError as e:
            errors.append(f"{where}: gene file not valid JSON: {e}")
            continue
        if data.get("id") != ref.split("/")[1] or data.get("domain") != ref.split("/")[0]:
            errors.append(f"{where}: anchor drift (id/domain vs ref)")
        if data.get("summary") != entry.get("summary"):
            errors.append(f"{where}: summary drift vs {p}")
        if data.get("signals") != entry.get("signals"):
            errors.append(f"{where}: signals drift vs {p}")

    refs = [e.get("ref") for e in genes if isinstance(e, dict) and isinstance(e.get("ref"), str)]
    if refs != sorted(refs):
        errors.append("manifest.json: genes must be sorted by ref")
    for ref in sorted(set(tree) - set(rows)):
        errors.append(f"manifest.json: missing gene {ref} (run scripts/gen-manifest.py)")
    for ref in sorted(set(rows) - set(tree)):
        errors.append(f"manifest.json: stale entry {ref} (file absent from genes/)")
    for ref, info in tree.items():
        if "_error" in info:
            errors.append(info["_error"])
    return len(tree) + len(genes), errors


def _self_test() -> int:
    def gene(domain: str, gid: str, summary: str = "s") -> str:
        return json.dumps({
            "id": gid, "domain": domain, "summary": summary,
            "signals": [f"{gid} signal"], "strategy": ["step"],
        }, ensure_ascii=False, indent=2) + "\n"

    def manifest_of(entries: list[dict]) -> str:
        return json.dumps({"version": 1, "genes": entries}, ensure_ascii=False, indent=2) + "\n"

    def entry(ref: str, summary: str = "s", signals: list | None = None) -> dict:
        return {"ref": ref, "path": f"genes/{ref}.json", "summary": summary,
                "signals": signals if signals is not None else [f"{ref.split('/')[1]} signal"]}

    def conforming(t: Path) -> None:
        (t / "genes/process").mkdir(parents=True)
        (t / "genes/doc").mkdir(parents=True)
        (t / "genes/process/alpha.json").write_text(gene("process", "alpha"), encoding="utf-8")
        (t / "genes/doc/beta.json").write_text(gene("doc", "beta"), encoding="utf-8")
        (t / "manifest.json").write_text(manifest_of(
            sorted([entry("doc/beta"), entry("process/alpha")], key=lambda e: e["ref"])), encoding="utf-8")

    cases = []
    cases.append((conforming, [], "manifest matching genes tree -> pass"))

    def missing_manifest(t: Path) -> None:
        (t / "genes/process").mkdir(parents=True)
        (t / "genes/process/alpha.json").write_text(gene("process", "alpha"), encoding="utf-8")
    cases.append((missing_manifest, ["manifest.json missing"], "no manifest -> fail"))

    def summary_drift(t: Path) -> None:
        conforming(t)
        (t / "manifest.json").write_text(manifest_of(
            sorted([entry("doc/beta"), entry("process/alpha", summary="edited")], key=lambda e: e["ref"])),
            encoding="utf-8")
    cases.append((summary_drift, ["summary drift"], "manifest summary drift -> fail"))

    def missing_row(t: Path) -> None:
        conforming(t)
        (t / "genes/doc/gamma.json").write_text(gene("doc", "gamma"), encoding="utf-8")
    cases.append((missing_row, ["missing gene doc/gamma"], "gene without manifest row -> fail"))

    def stale_row(t: Path) -> None:
        conforming(t)
        (t / "genes/doc/beta.json").unlink()
    cases.append((stale_row, ["stale entry doc/beta"], "manifest row without file -> fail"))

    def unsorted(t: Path) -> None:
        conforming(t)
        (t / "manifest.json").write_text(manifest_of(
            [entry("process/alpha"), entry("doc/beta")]), encoding="utf-8")
    cases.append((unsorted, ["must be sorted"], "unsorted refs -> fail"))

    def bad_path(t: Path) -> None:
        conforming(t)
        e = entry("doc/beta")
        e["path"] = "genes/doc/beta.yaml"
        (t / "manifest.json").write_text(manifest_of([entry("process/alpha"), e]), encoding="utf-8")
    cases.append((bad_path, ["path must be genes/"], "path not matching ref layout -> fail"))

    failed = 0
    with tempfile.TemporaryDirectory() as td:
        root = Path(td)
        for i, (builder, expected, desc) in enumerate(cases):
            t = root / f"case{i}"
            t.mkdir()
            builder(t)
            _, errors = verify(t)
            actual_ok = not errors
            want_ok = not expected
            if want_ok and actual_ok:
                print(f"  ok: {desc}")
            elif not want_ok and not actual_ok and any(any(sub in e for sub in expected) for e in errors):
                print(f"  ok: {desc}")
            else:
                print(f"  FAIL {desc}: expected {'pass' if want_ok else expected}, "
                      f"got {'pass' if actual_ok else errors}", file=sys.stderr)
                failed = 1
    if failed == 0:
        print("== verify-manifest self-test passed ==")
    else:
        print("== verify-manifest self-test failed ==", file=sys.stderr)
    return failed


def main() -> int:
    args = sys.argv[1:]
    if "--self-test" in args:
        return _self_test()
    repo = Path(args[args.index("--repo") + 1]) if "--repo" in args else Path(".")
    checked, errors = verify(repo)
    print(f"Checked manifest vs {checked} items")
    if errors:
        for e in errors:
            print(f"FAIL: {e}")
        return 1
    print("OK")
    return 0


if __name__ == "__main__":
    sys.exit(main())
